In [6]:
a=np.genfromtxt("winequality-red.csv", delimiter=",", skip_header=1)
a

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [9]:
type(a)


numpy.ndarray

In [11]:
b=a.astype(float)
b

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [13]:
c=np.shape(b)
c

(1599, 12)

In [14]:
print(b[2][3])

2.3


In [15]:
b.shape

(1599, 12)

In [20]:
print(b[0:3,3])

[1.9 2.6 2.3]


In [21]:
b[0:3,3]

array([1.9, 2.6, 2.3])

In [22]:
print(b[:,2])

[0.   0.   0.04 ... 0.13 0.12 0.47]


In [24]:
print(b[3,:])

[11.2    0.28   0.56   1.9    0.075 17.    60.     0.998  3.16   0.58
  9.8    6.   ]


In [25]:
b[1,5]

25.0

In [26]:
b[1,5]=10.0
b

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [27]:
b[1,5]

10.0

In [31]:
slice_new=b[:,9]
print(slice_new)
slice_new[:]=666
print(slice_new)

[0.56 0.68 0.65 ... 0.75 0.71 0.66]
[666. 666. 666. ... 666. 666. 666.]


In [39]:
type(b)

numpy.ndarray

In [64]:
b.dtype

dtype('float64')

In [68]:
d=b.astype(int)
print(d)

[[  7   0   0 ... 666   9  15]
 [  7   0   0 ... 666   9  15]
 [  7   0   0 ... 666   9  15]
 ...
 [  6   0   0 ... 666  11  16]
 [  5   0   0 ... 666  10  15]
 [  6   0   0 ... 666  11  16]]


In [61]:
d.dtype

dtype('int32')

In [66]:
e=d[:,11]-10

In [67]:
e

array([5, 5, 5, ..., 6, 5, 6])

In [69]:
d

array([[  7,   0,   0, ..., 666,   9,  15],
       [  7,   0,   0, ..., 666,   9,  15],
       [  7,   0,   0, ..., 666,   9,  15],
       ...,
       [  6,   0,   0, ..., 666,  11,  16],
       [  5,   0,   0, ..., 666,  10,  15],
       [  6,   0,   0, ..., 666,  11,  16]])

In [70]:
e=d[:,11]-10
e

array([5, 5, 5, ..., 6, 5, 6])

In [72]:
d[:,11]=e
d

array([[  7,   0,   0, ..., 666,   9,   5],
       [  7,   0,   0, ..., 666,   9,   5],
       [  7,   0,   0, ..., 666,   9,   5],
       ...,
       [  6,   0,   0, ..., 666,  11,   6],
       [  5,   0,   0, ..., 666,  10,   5],
       [  6,   0,   0, ..., 666,  11,   6]])

In [74]:
e=d[:,11]+10
e

array([15, 15, 15, ..., 16, 15, 16])

In [75]:
d[:,11]=e
d

array([[  7,   0,   0, ..., 666,   9,  15],
       [  7,   0,   0, ..., 666,   9,  15],
       [  7,   0,   0, ..., 666,   9,  15],
       ...,
       [  6,   0,   0, ..., 666,  11,  16],
       [  5,   0,   0, ..., 666,  10,  15],
       [  6,   0,   0, ..., 666,  11,  16]])

In [76]:
s=np.sum(d)
s

1226388

In [79]:
sc=np.sum(d,axis=0)
sc

array([  12589,      24,       1,    3350,       0,   25367,   74301,
            81,    4770, 1064934,   15969,   25002])

In [80]:
sr=np.sum(d,axis=1)
sr

array([746, 779, 771, ..., 773, 777, 765])

In [82]:
f=[i+i for i in d[:,11]]
print(f)

[30, 30, 30, 32, 30, 30, 30, 34, 34, 30, 30, 30, 30, 30, 30, 30, 34, 30, 28, 32, 32, 30, 30, 30, 32, 30, 30, 30, 30, 32, 30, 32, 30, 32, 30, 32, 32, 34, 28, 30, 30, 28, 32, 30, 30, 28, 30, 30, 30, 30, 30, 32, 32, 30, 32, 30, 30, 30, 30, 32, 30, 30, 34, 30, 30, 30, 30, 30, 30, 32, 32, 30, 30, 28, 30, 30, 30, 32, 30, 28, 30, 30, 30, 30, 32, 30, 32, 30, 30, 30, 30, 32, 30, 30, 28, 32, 30, 30, 30, 32, 32, 32, 32, 30, 30, 30, 30, 30, 32, 30, 30, 30, 30, 32, 30, 32, 32, 32, 32, 32, 30, 32, 30, 30, 30, 30, 30, 30, 34, 30, 30, 30, 30, 32, 32, 30, 30, 30, 30, 30, 30, 30, 32, 30, 32, 30, 30, 30, 32, 32, 32, 28, 30, 30, 30, 30, 30, 30, 30, 32, 30, 28, 32, 30, 30, 30, 30, 28, 32, 30, 28, 32, 32, 32, 30, 30, 30, 32, 30, 30, 30, 30, 30, 30, 32, 30, 30, 30, 30, 30, 30, 32, 30, 30, 30, 30, 30, 32, 34, 28, 34, 30, 30, 30, 32, 34, 34, 30, 30, 34, 32, 32, 32, 30, 32, 30, 30, 30, 30, 30, 32, 30, 30, 32, 28, 32, 32, 30, 32, 30, 34, 32, 32, 30, 32, 32, 32, 32, 32, 32, 30, 32, 32, 34, 34, 32, 30, 30, 32, 32,

In [83]:
d[:,11]=f
print(d)

[[  7   0   0 ... 666   9  30]
 [  7   0   0 ... 666   9  30]
 [  7   0   0 ... 666   9  30]
 ...
 [  6   0   0 ... 666  11  32]
 [  5   0   0 ... 666  10  30]
 [  6   0   0 ... 666  11  32]]


In [93]:
d[:,10]%=d[:,11]
d

array([[   7,    0,    0, ...,  666,    0,  900],
       [   7,    0,    0, ...,  666,    0,  900],
       [   7,    0,    0, ...,  666,    0,  900],
       ...,
       [   6,    0,    0, ...,  666,    0, 1024],
       [   5,    0,    0, ...,  666,    0,  900],
       [   6,    0,    0, ...,  666,    0, 1024]])

In [85]:
k=b[:,11]-10
b[:,11]=k

In [86]:
for i in b[:,11]:
    if(i>5):
        print(i)

6.0
7.0
7.0
7.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
7.0
6.0
6.0
6.0
6.0
6.0
7.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
7.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
7.0
7.0
6.0
7.0
7.0
7.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
7.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
7.0
7.0
6.0
6.0
6.0
6.0
6.0
6.0
7.0
7.0
8.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
8.0
7.0
6.0
7.0
7.0
6.0
6.0
7.0
7.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
7.0
6.0
7.0
6.0
6.0
6.0
7.0
6.0
6.0
6.0
6.0
7.0
7.0
6.0
6.0
7.0
6.0
6.0
6.0
6.0
6.0
7.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
7.0
7.0
6.0
6.0
7.0
6.0
7.0
7.0
6.0
6.0
6.0
7.0
6.0
7.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
7.0
8.0
6.0
7.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
7.0
6.0
6.0
7.0
6.0
6.0
7.0
7.0
7.0
7.0
6.0
6.0
6.0
7.0
6.0
6.0
6.0
6.0
6.0
8.0
6.0
7.0
7.0
7.0
6.0
6.0
6.0
6.0
6.0
6.0
7.0
8.0
7.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
6.0
8.0
6.0
6.0
7.0
6.0
6.0
7.0
7.0
6.0
6.0
8.0
6.0
8.0
6.0
6.0
7.0
7.0
7.0
7.0
7.0


In [89]:
c=0
for i in b[:,11]:
    if(i==10):
        c+=1
if(c!=0):
    print("Wines has Quality 10")
else:
    print("No wines has Quality 10")

No wines has Quality 10
